
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./api:/home
    networks:
      - chatbot-net
    environment:
      - OLLAMA_SERVER_URL=http://ollama:11434
      - MODEL_NAME=mistral
    depends_on:
      - ollama

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - 11434:11434
    volumes:
      - chatbot-vol:/root/.ollama
    networks:
      - chatbot-net
    environment:
      - MODEL_NAME=mistral
    entrypoint: [ "/usr/bin/bash", "pull-model.sh" ]

networks:
  chatbot-net:
    driver: bridge

volumes:
  chatbot-vol:
    driver: local